spring:
  application:
    name: JobTrackerApp

  datasource:
    url: jdbc:postgresql://localhost:5432/JobTrackerApp
    username: ${PG_DB_USERNAME}
    password: ${PG_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true